### ISSUE TITLE
issue building julia on termux

### ISSUE THREAD

**Issue by ajgiuliani** [its-pointless/julia#1]
hi,
I am trying to build julia on termux, but make fails:
In file included from /data/data/com.termux/files/home/src/julia/src/support/libsupport.h:13:
/data/data/com.termux/files/home/src/julia/src/support/ios.h:7:10: fatal error: 'uv.h' file not found

I am using the the buildjulia.sh script and all the necessary pkgs are installed. 
Any idea how to fix this.
Regards,
Alex

**Comment by its-pointless** [comment]
Don't build using make execute the script.

**Comment by ajgiuliani** [comment]
Sorry I was not clear. I did sh buildjulia-termux.sh and got this error during the process.

**Comment by ajgiuliani** [comment]
I am adding the full output of the execution the script, may it'll help identify the bug.


[buildjulia-termux.log](https://github.com/its-pointless/julia/files/2164392/buildjulia-termux.log)

**Comment by its-pointless** [comment]
Install patch

**Comment by ajgiuliani** [comment]
Great, it worked. Thank you very much this work.
